### ISSUE TITLE
code

### ISSUE THREAD

**Issue by harikrishnajiju** [harikrishnajiju/yt-mp3-downloader#1]

**Comment by GeorgeET15** [comment]
Hi, I would like to solve this issue. Can please describe it and can assign me. Thank you

**Comment by harikrishnajiju** [comment]
Hey, there I am trying to figure things out on GitHub! I didn't mean to add the label for the issue. Thank you for your interest :).

**Comment by GeorgeET15** [comment]
oh ok no problem have a nice day :)

**Comment by harikrishnajiju** [comment]
> oh ok no problem have a nice day :)

Thank you  :) 
You too buddy! All the best :)
